### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by ericalingyuan** [fgaim/biosses#1]
sh ./run.sh sample.txt 
#	WordNet	UMLS	Combined	QGRAM	PVM	SPRVSD
1.	0.857142857142857	0.857142857142857	0.9999999999999998	0.9599999785423279	NaN	score wordnet: 0.857142857142857
score umls: 0.857142857142857
combined score: 0.857142857142857
Exception in thread "main" java.lang.ExceptionInInitializerError
	at semanticSimilaritySystems.supervisedMethod.regressors.LinearRegressionMethod.getSimilarity(LinearRegressionMethod.java:104)
	at nlpcl.cmd.main(cmd.java:137)
Caused by: java.lang.IllegalArgumentException: resource paragraphVectors/paragVecModel.zip not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
	at com.google.common.io.Resources.getResource(Resources.java:197)
	at semanticSimilaritySystems.unsupervisedMethod.paragraphVector.SentenceVectorsBasedSimilarity.<clinit>(SentenceVectorsBasedSimilarity.java:32)
	... 2 more

I am trying to run: sh ./run.sh sample.txt 
but it shows errors. I checked the "paragVecModel.zip" file exists in the /biosses/src/main/resources/paragraphvectors folder.
Thank you!

**Comment by fgaim** [comment]
@ericalingyuan please use the actively maintained repo at https://github.com/gizemsogancioglu/biosses; if the issue persists we will check it from there.

**Comment by kaushikacharya** [comment]
> @ericalingyuan please use the actively maintained repo at https://github.com/gizemsogancioglu/biosses; if the issue persists we will check it from there.

@fgaim 
Please mention this in the description of the repository so that users know which repository to follow.
